# -*- coding: utf-8 -*-
"""Workshop-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gZ_w81bM-xRPsGnEA2nmMTkyb8T6hna0

#Prashna Prajapati

#Exercise on Loops

#Display Fibonacci series up to 10 terms.
"""

n = 10

a, b = 0, 1

print("Fibonacci series up to", n, "terms:")

for i in range(n):
    print(a, end=" ")
    a, b = b, a + b

"""# Find the factorial of a given number. Ask the user to provide the number.

"""

num = int(input("Enter a number: "))

factorial = 1
if num < 0:
  print("Factorial does not exist for negative numbers")
elif num == 0:
  print("The factorial of 0 is 1.")
else:
  for i in range(1, num + 1):
    factorial = factorial * i
  print("The factorial of", num, "is", factorial)

"""#Write a program to print a right angle triangle using the for loop.

"""

rows = int(input("Enter the number of rows: "))

for i in range(1, rows + 1):
    print("*" * i)

"""#Exercise on Functions

# Make a simple calculator that can add, subtract, multiply and divide two numbers using function
"""

def add(x, y):
    return x + y

def subtract(x, y):
    return x - y

def multiply(x, y):
    return x * y

def divide(x, y):
  if y == 0:
    return "Cannot divide by zero"
  else:
    return x / y

num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))

print("\nSelect operation:")
print("1. Add")
print("2. Subtract")
print("3. Multiply")
print("4. Divide")

choice = input("Enter choice (1/2/3/4): ")

if choice == '1':
    print("Result:", add(num1, num2))
elif choice == '2':
    print("Result:", subtract(num1, num2))
elif choice == '3':
    print("Result:", multiply(num1, num2))
elif choice == '4':
    print("Result:", divide(num1, num2))
else:
    print("Invalid choice!")

"""#Exercise on List and Dictionaries

#Remove the first duplicate element of a list
"""

numbers = [1, 2, 3, 4, 5, 3, 4, 2]

seen = set()

for i in range(len(numbers)):
  if numbers[i] in seen:
    numbers.pop(i)
    break
  else:
    seen.add(numbers[i])

print("List after removing first duplicate elements: ")
print(numbers)

"""#Write a Python program to create a new dictionary by extracting the mentioned keys from the below dictionary.

sample_dict = { "name": "Anderson", "age": 35, "salary": 5000, "city": "London"}

keys = ["name", "salary"]
"""

sample_dict = {"name": "Anderson","age": 35,"salary": 5000,"city": "London"}

keys = ["name", "salary"]

new_dict = {}

for key in keys:
    new_dict[key] = sample_dict[key]

print("New dictionary:", new_dict)

"""#Write a Python program to convert two lists into a dictionary in a way that item from list_one is the key and item from list_two is the value.

list_one = ['one', 'two', 'three']

list_two = [1, 2, 3]

"""

list_one = ['one', 'two', 'three']
list_two = [1, 2, 3]

new_dict = {}

for i in range (len(list_one)):
  new_dict[list_one[i]] = list_two[i]

print("Dictonary:", new_dict)